num_train_epochs: 25
learning_rat: 0.0001
save_total_limit: 45
lr_scheduler_type:  'cosine'
evaluation_strategy: 'epoch'
per_device_train_batch_size:  32
per_device_eval_batch_size: 32
output_dir: "path/to/output/dir"
overwrite_output_dir: True
load_best_model_at_end: True
remove_unused_columns:  False
metric_for_best_model: 'f1'
optim: 'adamw_torch'
save_strategy:  'epoch'